name: Azure deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv/
          source ./antenv/bin/activate
          pip3 install --upgrade pip
          # python -m pip install fastapi uvicorn gunicorn
          echo "uvicorn version is::"
          uvicorn --version
          pip3 list
          pip3 install -r requirements.txt
          
      - name: publish
        run: echo "Publishing..."

      - name: Deploying
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'test-fastapi'
          publish-profile: ${{ secrets.AZURE_PYTHON_PROFILE }}
          package: '.'
