name: Azure deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: publish
        run: echo "Publishing..."

      - name: Deploying
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'campus-connect-plus-plus-backend'
          pulish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.'
